# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.3

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake.exe

# The command to remove a file.
RM = /usr/bin/cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/Shahm/ucd-csci2312-pa5

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/Shahm/ucd-csci2312-pa5

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/Shahm/ucd-csci2312-pa5/CMakeFiles /home/Shahm/ucd-csci2312-pa5/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/Shahm/ucd-csci2312-pa5/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ucd_csci2312_pa5

# Build rule for target.
ucd_csci2312_pa5: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ucd_csci2312_pa5
.PHONY : ucd_csci2312_pa5

# fast build rule for target.
ucd_csci2312_pa5/fast:
	$(MAKE) -f CMakeFiles/ucd_csci2312_pa5.dir/build.make CMakeFiles/ucd_csci2312_pa5.dir/build
.PHONY : ucd_csci2312_pa5/fast

ErrorContext.o: ErrorContext.cpp.o

.PHONY : ErrorContext.o

# target to build an object file
ErrorContext.cpp.o:
	$(MAKE) -f CMakeFiles/ucd_csci2312_pa5.dir/build.make CMakeFiles/ucd_csci2312_pa5.dir/ErrorContext.cpp.o
.PHONY : ErrorContext.cpp.o

ErrorContext.i: ErrorContext.cpp.i

.PHONY : ErrorContext.i

# target to preprocess a source file
ErrorContext.cpp.i:
	$(MAKE) -f CMakeFiles/ucd_csci2312_pa5.dir/build.make CMakeFiles/ucd_csci2312_pa5.dir/ErrorContext.cpp.i
.PHONY : ErrorContext.cpp.i

ErrorContext.s: ErrorContext.cpp.s

.PHONY : ErrorContext.s

# target to generate assembly for a file
ErrorContext.cpp.s:
	$(MAKE) -f CMakeFiles/ucd_csci2312_pa5.dir/build.make CMakeFiles/ucd_csci2312_pa5.dir/ErrorContext.cpp.s
.PHONY : ErrorContext.cpp.s

TemplateTests.o: TemplateTests.cpp.o

.PHONY : TemplateTests.o

# target to build an object file
TemplateTests.cpp.o:
	$(MAKE) -f CMakeFiles/ucd_csci2312_pa5.dir/build.make CMakeFiles/ucd_csci2312_pa5.dir/TemplateTests.cpp.o
.PHONY : TemplateTests.cpp.o

TemplateTests.i: TemplateTests.cpp.i

.PHONY : TemplateTests.i

# target to preprocess a source file
TemplateTests.cpp.i:
	$(MAKE) -f CMakeFiles/ucd_csci2312_pa5.dir/build.make CMakeFiles/ucd_csci2312_pa5.dir/TemplateTests.cpp.i
.PHONY : TemplateTests.cpp.i

TemplateTests.s: TemplateTests.cpp.s

.PHONY : TemplateTests.s

# target to generate assembly for a file
TemplateTests.cpp.s:
	$(MAKE) -f CMakeFiles/ucd_csci2312_pa5.dir/build.make CMakeFiles/ucd_csci2312_pa5.dir/TemplateTests.cpp.s
.PHONY : TemplateTests.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/ucd_csci2312_pa5.dir/build.make CMakeFiles/ucd_csci2312_pa5.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/ucd_csci2312_pa5.dir/build.make CMakeFiles/ucd_csci2312_pa5.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/ucd_csci2312_pa5.dir/build.make CMakeFiles/ucd_csci2312_pa5.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ucd_csci2312_pa5"
	@echo "... ErrorContext.o"
	@echo "... ErrorContext.i"
	@echo "... ErrorContext.s"
	@echo "... TemplateTests.o"
	@echo "... TemplateTests.i"
	@echo "... TemplateTests.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

